package ormc

import "webtyp.com/model"

import (
	"os"
	"path/filepath"
	"testing"
)

func TestParseGenerated(t *testing.T) {
	// MS1: parseGenerated on a local fixture *_orm.go
	content := `// DO NOT EDIT. generated by webtyp.com/orm
package test

import "webtyp.com/model"

import "webtyp.com/fmt"

func (m *CatalogItem) ModelName() string {
	return "catalog_item"
}

var _schemaCatalogItem = []model.Field{
	{Name: "id", Type: model.FieldText, DB: &model.FieldDB{PK: true}},
	{Name: "name", Type: model.FieldText, NotNull: true},
	{Name: "price", Type: model.FieldInt},
	{Name: "active", Type: model.FieldBool},
}

func (m *CatalogItem) Schema() []model.Field { return _schemaCatalogItem }
func (m *CatalogItem) Pointers() []any { return nil }
`
	tmpDir, _ := os.MkdirTemp("", "ormc_test")
	defer os.RemoveAll(tmpDir)

	path := filepath.Join(tmpDir, "item_orm.go")
	os.WriteFile(path, []byte(content), 0644)

	schemas, err := parseGenerated(path)
	if err != nil {
		t.Fatal(err)
	}

	fields, ok := schemas["catalog_item"]
	if !ok {
		t.Fatal("table catalog_item not found")
	}

	if len(fields) != 4 {
		t.Fatalf("expected 4 fields, got %d", len(fields))
	}

	if fields[0].Name != "id" || fields[0].Type.Storage() != model.FieldText || fields[0].DB == nil || !fields[0].DB.PK {
		t.Errorf("field 0 mismatch: %+v", fields[0])
	}

	if fields[1].Name != "name" || !fields[1].NotNull {
		t.Errorf("field 1 mismatch: %+v", fields[1])
	}
}

func TestParseGenerated_MS2(t *testing.T) {
	// MS2: parseGenerated PK/Unique/AutoInc
	content := `package test
import "webtyp.com/fmt"

func (m *User) ModelName() string { return "users" }
var _schemaUser = []model.Field{
	{Name: "id", Type: model.FieldInt, DB: &model.FieldDB{PK: true, AutoInc: true}},
	{Name: "email", Type: model.FieldText, DB: &model.FieldDB{Unique: true}},
}
`
	tmpDir, _ := os.MkdirTemp("", "ormc_test")
	defer os.RemoveAll(tmpDir)

	path := filepath.Join(tmpDir, "user_orm.go")
	os.WriteFile(path, []byte(content), 0644)

	schemas, err := parseGenerated(path)
	if err != nil {
		t.Fatal(err)
	}

	fields := schemas["users"]
	if !fields[0].DB.PK || !fields[0].DB.AutoInc {
		t.Errorf("id field DB mismatch: %+v", fields[0].DB)
	}
	if !fields[1].DB.Unique {
		t.Errorf("email field DB mismatch: %+v", fields[1].DB)
	}
}

func TestParseGenerated_NoDB(t *testing.T) {
	// orm:no_db structs: ModelName() is always emitted (used by form/API layers)
	// but ReadOne*/ReadAll* are absent. parseGenerated must not include them in
	// the sync map — otherwise ScanModules would create spurious tables.
	content := `package test
import "webtyp.com/fmt"
import "webtyp.com/orm"

func (m *User) ModelName() string { return "users" }
var _schemaUser = []model.Field{
	{Name: "id", Type: model.FieldInt, DB: &model.FieldDB{PK: true, AutoInc: true}},
	{Name: "name", Type: model.FieldText, NotNull: true},
}
func (m *User) Schema() []model.Field { return _schemaUser }
func (m *User) Pointers() []any     { return nil }
func ReadOneUser(qb *orm.QB, model *User) (*User, error) { return nil, nil }

func (m *FormArgs) ModelName() string { return "form_args" }
var _schemaFormArgs = []model.Field{
	{Name: "sql", Type: model.FieldText, NotNull: true},
}
func (m *FormArgs) Schema() []model.Field { return _schemaFormArgs }
func (m *FormArgs) Pointers() []any     { return nil }
`
	tmpDir, _ := os.MkdirTemp("", "ormc_test")
	defer os.RemoveAll(tmpDir)

	path := filepath.Join(tmpDir, "models_orm.go")
	os.WriteFile(path, []byte(content), 0644)

	schemas, err := parseGenerated(path)
	if err != nil {
		t.Fatal(err)
	}

	if _, ok := schemas["users"]; !ok {
		t.Error("users table should be present (has ReadOne)")
	}
	if _, ok := schemas["form_args"]; ok {
		t.Error("form_args table must NOT be present (orm:no_db — no ReadOne/ReadAll)")
	}
}

func TestParseGenerated_MS7(t *testing.T) {
	// MS7: unknown model.FieldXxx in literal
	content := `package test
import "webtyp.com/fmt"

func (m *X) ModelName() string { return "x" }
var _schemaX = []model.Field{
	{Name: "a", Type: model.FieldText},
	{Name: "b", Type: model.FieldUnknown},
}
`
	tmpDir, _ := os.MkdirTemp("", "ormc_test")
	defer os.RemoveAll(tmpDir)

	path := filepath.Join(tmpDir, "x_orm.go")
	os.WriteFile(path, []byte(content), 0644)

	schemas, err := parseGenerated(path)
	if err != nil {
		t.Fatal(err)
	}

	fields := schemas["x"]
	if len(fields) != 2 {
		t.Fatal("expected 2 fields")
	}
	if fields[1].Type != nil {
		t.Errorf("expected nil for unknown type, got %v", fields[1].Type)
	}
}
