// DO NOT EDIT. generated by webtyp.com/ormc

package tests

import (
	"webtyp.com/model"
	"webtyp.com/orm"
)

type User struct {
	Id int64
	FirstName string
	LastName string
	Email string
	Score float64
	IsActive bool
	Avatar []byte
}

func (m *User) ModelName() string { return "user" }

func (m *User) Schema() []model.Field { return UserModel.Fields }

func (m *User) Pointers() []any { return []any{&m.Id, &m.FirstName, &m.LastName, &m.Email, &m.Score, &m.IsActive, &m.Avatar} }

func (m *User) IsNil() bool { return m == nil }

func (m *User) EncodeFields(w model.FieldWriter) {
	w.Int("id", m.Id)
	w.String("first_name", m.FirstName)
	w.String("last_name", m.LastName)
	w.String("email", m.Email)
	w.Float("score", m.Score)
	w.Bool("is_active", m.IsActive)
	w.Bytes("avatar", m.Avatar)
}

func (m *User) DecodeFields(r model.FieldReader) {
	if v, ok := r.Int("id"); ok { m.Id = v }
	if v, ok := r.String("first_name"); ok { m.FirstName = v }
	if v, ok := r.String("last_name"); ok { m.LastName = v }
	if v, ok := r.String("email"); ok { m.Email = v }
	if v, ok := r.Float("score"); ok { m.Score = v }
	if v, ok := r.Bool("is_active"); ok { m.IsActive = v }
	if v, ok := r.Bytes("avatar"); ok { m.Avatar = v }
}

type UserList []*User

func (s *UserList) Schema() []model.Field { return nil }
func (s *UserList) Pointers() []any     { return nil }
func (s *UserList) Len() int             { return len(*s) }
func (s *UserList) At(i int) model.Fielder { return (*s)[i] }
func (s *UserList) Append() model.Fielder  { v := &User{}; *s = append(*s, v); return v }
func (s *UserList) IsNil() bool          { return s == nil }
func (s *UserList) EncodeFields(_ model.FieldWriter) {}
func (s *UserList) DecodeFields(_ model.FieldReader) {}

func (m *User) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var User_ = struct {
	Id string
	FirstName string
	LastName string
	Email string
	Score string
	IsActive string
	Avatar string
}{
	Id: "id",
	FirstName: "first_name",
	LastName: "last_name",
	Email: "email",
	Score: "score",
	IsActive: "is_active",
	Avatar: "avatar",
}

func ReadOneUser(qb *orm.QB, model *User) (*User, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllUser(qb *orm.QB) (UserList, error) {
	var results UserList
	err := qb.ReadAll(
		func() model.Model { return &User{} },
		func(m model.Model) { results = append(results, m.(*User)) },
	)
	return results, err
}

type Order struct {
	Id string
	UserId int64
	Total float64
}

func (m *Order) ModelName() string { return "order" }

func (m *Order) Schema() []model.Field { return OrderModel.Fields }

func (m *Order) Pointers() []any { return []any{&m.Id, &m.UserId, &m.Total} }

func (m *Order) IsNil() bool { return m == nil }

func (m *Order) EncodeFields(w model.FieldWriter) {
	w.String("id", m.Id)
	w.Int("user_id", m.UserId)
	w.Float("total", m.Total)
}

func (m *Order) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok { m.Id = v }
	if v, ok := r.Int("user_id"); ok { m.UserId = v }
	if v, ok := r.Float("total"); ok { m.Total = v }
}

type OrderList []*Order

func (s *OrderList) Schema() []model.Field { return nil }
func (s *OrderList) Pointers() []any     { return nil }
func (s *OrderList) Len() int             { return len(*s) }
func (s *OrderList) At(i int) model.Fielder { return (*s)[i] }
func (s *OrderList) Append() model.Fielder  { v := &Order{}; *s = append(*s, v); return v }
func (s *OrderList) IsNil() bool          { return s == nil }
func (s *OrderList) EncodeFields(_ model.FieldWriter) {}
func (s *OrderList) DecodeFields(_ model.FieldReader) {}

func (m *Order) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var Order_ = struct {
	Id string
	UserId string
	Total string
}{
	Id: "id",
	UserId: "user_id",
	Total: "total",
}

func ReadOneOrder(qb *orm.QB, model *Order) (*Order, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllOrder(qb *orm.QB) (OrderList, error) {
	var results OrderList
	err := qb.ReadAll(
		func() model.Model { return &Order{} },
		func(m model.Model) { results = append(results, m.(*Order)) },
	)
	return results, err
}

func (m *Order) SchemaExt() []model.FieldExt {
	return []model.FieldExt{
		{Field: OrderModel.Fields[1], Ref: "user", RefColumn: "id", OnDelete: ""},
	}
}

type ModelWithIgnored struct {
	Id string
	Name string
	Tags string
	Score float64
}

func (m *ModelWithIgnored) ModelName() string { return "model_with_ignored" }

var _schemaModelWithIgnored = []model.Field{
		{Name: "id", Type: model.Text(), DB: &model.FieldDB{PK: true}},
		{Name: "name", Type: model.Text()},
		{Name: "score", Type: model.Float()},
	}

func (m *ModelWithIgnored) Schema() []model.Field { return _schemaModelWithIgnored }

func (m *ModelWithIgnored) Pointers() []any { return []any{&m.Id, &m.Name, &m.Score} }

func (m *ModelWithIgnored) IsNil() bool { return m == nil }

func (m *ModelWithIgnored) EncodeFields(w model.FieldWriter) {
	w.String("id", m.Id)
	w.String("name", m.Name)
	w.Float("score", m.Score)
}

func (m *ModelWithIgnored) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok { m.Id = v }
	if v, ok := r.String("name"); ok { m.Name = v }
	if v, ok := r.Float("score"); ok { m.Score = v }
}

type ModelWithIgnoredList []*ModelWithIgnored

func (s *ModelWithIgnoredList) Schema() []model.Field { return nil }
func (s *ModelWithIgnoredList) Pointers() []any     { return nil }
func (s *ModelWithIgnoredList) Len() int             { return len(*s) }
func (s *ModelWithIgnoredList) At(i int) model.Fielder { return (*s)[i] }
func (s *ModelWithIgnoredList) Append() model.Fielder  { v := &ModelWithIgnored{}; *s = append(*s, v); return v }
func (s *ModelWithIgnoredList) IsNil() bool          { return s == nil }
func (s *ModelWithIgnoredList) EncodeFields(_ model.FieldWriter) {}
func (s *ModelWithIgnoredList) DecodeFields(_ model.FieldReader) {}

func (m *ModelWithIgnored) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var ModelWithIgnored_ = struct {
	Id string
	Name string
	Tags string
	Score string
}{
	Id: "id",
	Name: "name",
	Tags: "tags",
	Score: "score",
}

func ReadOneModelWithIgnored(qb *orm.QB, model *ModelWithIgnored) (*ModelWithIgnored, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllModelWithIgnored(qb *orm.QB) (ModelWithIgnoredList, error) {
	var results ModelWithIgnoredList
	err := qb.ReadAll(
		func() model.Model { return &ModelWithIgnored{} },
		func(m model.Model) { results = append(results, m.(*ModelWithIgnored)) },
	)
	return results, err
}

type MultiA struct {
	Id string
	Name string
}

func (m *MultiA) ModelName() string { return "multi_a_records" }

func (m *MultiA) Schema() []model.Field { return MultiAModel.Fields }

func (m *MultiA) Pointers() []any { return []any{&m.Id, &m.Name} }

func (m *MultiA) IsNil() bool { return m == nil }

func (m *MultiA) EncodeFields(w model.FieldWriter) {
	w.String("id", m.Id)
	w.String("name", m.Name)
}

func (m *MultiA) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok { m.Id = v }
	if v, ok := r.String("name"); ok { m.Name = v }
}

type MultiAList []*MultiA

func (s *MultiAList) Schema() []model.Field { return nil }
func (s *MultiAList) Pointers() []any     { return nil }
func (s *MultiAList) Len() int             { return len(*s) }
func (s *MultiAList) At(i int) model.Fielder { return (*s)[i] }
func (s *MultiAList) Append() model.Fielder  { v := &MultiA{}; *s = append(*s, v); return v }
func (s *MultiAList) IsNil() bool          { return s == nil }
func (s *MultiAList) EncodeFields(_ model.FieldWriter) {}
func (s *MultiAList) DecodeFields(_ model.FieldReader) {}

func (m *MultiA) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var MultiA_ = struct {
	Id string
	Name string
}{
	Id: "id",
	Name: "name",
}

func ReadOneMultiA(qb *orm.QB, model *MultiA) (*MultiA, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllMultiA(qb *orm.QB) (MultiAList, error) {
	var results MultiAList
	err := qb.ReadAll(
		func() model.Model { return &MultiA{} },
		func(m model.Model) { results = append(results, m.(*MultiA)) },
	)
	return results, err
}

type MultiB struct {
	Id string
	Value int64
}

func (m *MultiB) ModelName() string { return "multi_b" }

func (m *MultiB) Schema() []model.Field { return MultiBModel.Fields }

func (m *MultiB) Pointers() []any { return []any{&m.Id, &m.Value} }

func (m *MultiB) IsNil() bool { return m == nil }

func (m *MultiB) EncodeFields(w model.FieldWriter) {
	w.String("id", m.Id)
	w.Int("value", m.Value)
}

func (m *MultiB) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok { m.Id = v }
	if v, ok := r.Int("value"); ok { m.Value = v }
}

type MultiBList []*MultiB

func (s *MultiBList) Schema() []model.Field { return nil }
func (s *MultiBList) Pointers() []any     { return nil }
func (s *MultiBList) Len() int             { return len(*s) }
func (s *MultiBList) At(i int) model.Fielder { return (*s)[i] }
func (s *MultiBList) Append() model.Fielder  { v := &MultiB{}; *s = append(*s, v); return v }
func (s *MultiBList) IsNil() bool          { return s == nil }
func (s *MultiBList) EncodeFields(_ model.FieldWriter) {}
func (s *MultiBList) DecodeFields(_ model.FieldReader) {}

func (m *MultiB) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var MultiB_ = struct {
	Id string
	Value string
}{
	Id: "id",
	Value: "value",
}

func ReadOneMultiB(qb *orm.QB, model *MultiB) (*MultiB, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllMultiB(qb *orm.QB) (MultiBList, error) {
	var results MultiBList
	err := qb.ReadAll(
		func() model.Model { return &MultiB{} },
		func(m model.Model) { results = append(results, m.(*MultiB)) },
	)
	return results, err
}

type NumericTypes struct {
	IdNumeric int64
	CountUint int64
	RatioF32 float64
}

func (m *NumericTypes) ModelName() string { return "numeric_types" }

func (m *NumericTypes) Schema() []model.Field { return NumericTypesModel.Fields }

func (m *NumericTypes) Pointers() []any { return []any{&m.IdNumeric, &m.CountUint, &m.RatioF32} }

func (m *NumericTypes) IsNil() bool { return m == nil }

func (m *NumericTypes) EncodeFields(w model.FieldWriter) {
	w.Int("id_numeric", m.IdNumeric)
	w.Int("count_uint", m.CountUint)
	w.Float("ratio_f32", m.RatioF32)
}

func (m *NumericTypes) DecodeFields(r model.FieldReader) {
	if v, ok := r.Int("id_numeric"); ok { m.IdNumeric = v }
	if v, ok := r.Int("count_uint"); ok { m.CountUint = v }
	if v, ok := r.Float("ratio_f32"); ok { m.RatioF32 = v }
}

type NumericTypesList []*NumericTypes

func (s *NumericTypesList) Schema() []model.Field { return nil }
func (s *NumericTypesList) Pointers() []any     { return nil }
func (s *NumericTypesList) Len() int             { return len(*s) }
func (s *NumericTypesList) At(i int) model.Fielder { return (*s)[i] }
func (s *NumericTypesList) Append() model.Fielder  { v := &NumericTypes{}; *s = append(*s, v); return v }
func (s *NumericTypesList) IsNil() bool          { return s == nil }
func (s *NumericTypesList) EncodeFields(_ model.FieldWriter) {}
func (s *NumericTypesList) DecodeFields(_ model.FieldReader) {}

func (m *NumericTypes) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var NumericTypes_ = struct {
	IdNumeric string
	CountUint string
	RatioF32 string
}{
	IdNumeric: "id_numeric",
	CountUint: "count_uint",
	RatioF32: "ratio_f32",
}

func ReadOneNumericTypes(qb *orm.QB, model *NumericTypes) (*NumericTypes, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllNumericTypes(qb *orm.QB) (NumericTypesList, error) {
	var results NumericTypesList
	err := qb.ReadAll(
		func() model.Model { return &NumericTypes{} },
		func(m model.Model) { results = append(results, m.(*NumericTypes)) },
	)
	return results, err
}

type RefNoColumn struct {
	IdRef string
	ParentId int64
}

func (m *RefNoColumn) ModelName() string { return "ref_no_column" }

func (m *RefNoColumn) Schema() []model.Field { return RefNoColumnModel.Fields }

func (m *RefNoColumn) Pointers() []any { return []any{&m.IdRef, &m.ParentId} }

func (m *RefNoColumn) IsNil() bool { return m == nil }

func (m *RefNoColumn) EncodeFields(w model.FieldWriter) {
	w.String("id_ref", m.IdRef)
	w.Int("parent_id", m.ParentId)
}

func (m *RefNoColumn) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id_ref"); ok { m.IdRef = v }
	if v, ok := r.Int("parent_id"); ok { m.ParentId = v }
}

type RefNoColumnList []*RefNoColumn

func (s *RefNoColumnList) Schema() []model.Field { return nil }
func (s *RefNoColumnList) Pointers() []any     { return nil }
func (s *RefNoColumnList) Len() int             { return len(*s) }
func (s *RefNoColumnList) At(i int) model.Fielder { return (*s)[i] }
func (s *RefNoColumnList) Append() model.Fielder  { v := &RefNoColumn{}; *s = append(*s, v); return v }
func (s *RefNoColumnList) IsNil() bool          { return s == nil }
func (s *RefNoColumnList) EncodeFields(_ model.FieldWriter) {}
func (s *RefNoColumnList) DecodeFields(_ model.FieldReader) {}

func (m *RefNoColumn) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var RefNoColumn_ = struct {
	IdRef string
	ParentId string
}{
	IdRef: "id_ref",
	ParentId: "parent_id",
}

func ReadOneRefNoColumn(qb *orm.QB, model *RefNoColumn) (*RefNoColumn, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllRefNoColumn(qb *orm.QB) (RefNoColumnList, error) {
	var results RefNoColumnList
	err := qb.ReadAll(
		func() model.Model { return &RefNoColumn{} },
		func(m model.Model) { results = append(results, m.(*RefNoColumn)) },
	)
	return results, err
}

func (m *RefNoColumn) SchemaExt() []model.FieldExt {
	return []model.FieldExt{
		{Field: RefNoColumnModel.Fields[1], Ref: "multi_a", RefColumn: "", OnDelete: ""},
	}
}

type PointerReceiver struct {
	Id string
	Name string
}

func (m *PointerReceiver) ModelName() string { return "ptr_table" }

func (m *PointerReceiver) Schema() []model.Field { return PointerReceiverModel.Fields }

func (m *PointerReceiver) Pointers() []any { return []any{&m.Id, &m.Name} }

func (m *PointerReceiver) IsNil() bool { return m == nil }

func (m *PointerReceiver) EncodeFields(w model.FieldWriter) {
	w.String("id", m.Id)
	w.String("name", m.Name)
}

func (m *PointerReceiver) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok { m.Id = v }
	if v, ok := r.String("name"); ok { m.Name = v }
}

type PointerReceiverList []*PointerReceiver

func (s *PointerReceiverList) Schema() []model.Field { return nil }
func (s *PointerReceiverList) Pointers() []any     { return nil }
func (s *PointerReceiverList) Len() int             { return len(*s) }
func (s *PointerReceiverList) At(i int) model.Fielder { return (*s)[i] }
func (s *PointerReceiverList) Append() model.Fielder  { v := &PointerReceiver{}; *s = append(*s, v); return v }
func (s *PointerReceiverList) IsNil() bool          { return s == nil }
func (s *PointerReceiverList) EncodeFields(_ model.FieldWriter) {}
func (s *PointerReceiverList) DecodeFields(_ model.FieldReader) {}

func (m *PointerReceiver) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var PointerReceiver_ = struct {
	Id string
	Name string
}{
	Id: "id",
	Name: "name",
}

func ReadOnePointerReceiver(qb *orm.QB, model *PointerReceiver) (*PointerReceiver, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllPointerReceiver(qb *orm.QB) (PointerReceiverList, error) {
	var results PointerReceiverList
	err := qb.ReadAll(
		func() model.Model { return &PointerReceiver{} },
		func(m model.Model) { results = append(results, m.(*PointerReceiver)) },
	)
	return results, err
}

type UserForm struct {
	Id string
	Name string
	Email string
	Password string
	Bio string
	Age int64
}

func (m *UserForm) ModelName() string { return "user_form" }

func (m *UserForm) Schema() []model.Field { return UserFormModel.Fields }

func (m *UserForm) Pointers() []any { return []any{&m.Id, &m.Name, &m.Email, &m.Password, &m.Bio, &m.Age} }

func (m *UserForm) IsNil() bool { return m == nil }

func (m *UserForm) EncodeFields(w model.FieldWriter) {
	w.String("id", m.Id)
	w.String("name", m.Name)
	w.String("email", m.Email)
	w.String("password", m.Password)
	w.String("bio", m.Bio)
	w.Int("age", m.Age)
}

func (m *UserForm) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok { m.Id = v }
	if v, ok := r.String("name"); ok { m.Name = v }
	if v, ok := r.String("email"); ok { m.Email = v }
	if v, ok := r.String("password"); ok { m.Password = v }
	if v, ok := r.String("bio"); ok { m.Bio = v }
	if v, ok := r.Int("age"); ok { m.Age = v }
}

type UserFormList []*UserForm

func (s *UserFormList) Schema() []model.Field { return nil }
func (s *UserFormList) Pointers() []any     { return nil }
func (s *UserFormList) Len() int             { return len(*s) }
func (s *UserFormList) At(i int) model.Fielder { return (*s)[i] }
func (s *UserFormList) Append() model.Fielder  { v := &UserForm{}; *s = append(*s, v); return v }
func (s *UserFormList) IsNil() bool          { return s == nil }
func (s *UserFormList) EncodeFields(_ model.FieldWriter) {}
func (s *UserFormList) DecodeFields(_ model.FieldReader) {}

func (m *UserForm) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var UserForm_ = struct {
	Id string
	Name string
	Email string
	Password string
	Bio string
	Age string
}{
	Id: "id",
	Name: "name",
	Email: "email",
	Password: "password",
	Bio: "bio",
	Age: "age",
}

func ReadOneUserForm(qb *orm.QB, model *UserForm) (*UserForm, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllUserForm(qb *orm.QB) (UserFormList, error) {
	var results UserFormList
	err := qb.ReadAll(
		func() model.Model { return &UserForm{} },
		func(m model.Model) { results = append(results, m.(*UserForm)) },
	)
	return results, err
}

type LoginForm struct {
	Email string
	Password string
}

func (m *LoginForm) ModelName() string { return "login_form" }

func (m *LoginForm) Schema() []model.Field { return LoginFormModel.Fields }

func (m *LoginForm) Pointers() []any { return []any{&m.Email, &m.Password} }

func (m *LoginForm) IsNil() bool { return m == nil }

func (m *LoginForm) EncodeFields(w model.FieldWriter) {
	w.String("email", m.Email)
	w.String("password", m.Password)
}

func (m *LoginForm) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("email"); ok { m.Email = v }
	if v, ok := r.String("password"); ok { m.Password = v }
}

type LoginFormList []*LoginForm

func (s *LoginFormList) Schema() []model.Field { return nil }
func (s *LoginFormList) Pointers() []any     { return nil }
func (s *LoginFormList) Len() int             { return len(*s) }
func (s *LoginFormList) At(i int) model.Fielder { return (*s)[i] }
func (s *LoginFormList) Append() model.Fielder  { v := &LoginForm{}; *s = append(*s, v); return v }
func (s *LoginFormList) IsNil() bool          { return s == nil }
func (s *LoginFormList) EncodeFields(_ model.FieldWriter) {}
func (s *LoginFormList) DecodeFields(_ model.FieldReader) {}

func (m *LoginForm) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type Address struct {
	Street string
	City string
}

func (m *Address) ModelName() string { return "address" }

func (m *Address) Schema() []model.Field { return AddressModel.Fields }

func (m *Address) Pointers() []any { return []any{&m.Street, &m.City} }

func (m *Address) IsNil() bool { return m == nil }

func (m *Address) EncodeFields(w model.FieldWriter) {
	w.String("street", m.Street)
	w.String("city", m.City)
}

func (m *Address) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("street"); ok { m.Street = v }
	if v, ok := r.String("city"); ok { m.City = v }
}

type AddressList []*Address

func (s *AddressList) Schema() []model.Field { return nil }
func (s *AddressList) Pointers() []any     { return nil }
func (s *AddressList) Len() int             { return len(*s) }
func (s *AddressList) At(i int) model.Fielder { return (*s)[i] }
func (s *AddressList) Append() model.Fielder  { v := &Address{}; *s = append(*s, v); return v }
func (s *AddressList) IsNil() bool          { return s == nil }
func (s *AddressList) EncodeFields(_ model.FieldWriter) {}
func (s *AddressList) DecodeFields(_ model.FieldReader) {}

func (m *Address) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type UserWithComposition struct {
	Id string
	Name string
	HomeAddr Address
}

func (m *UserWithComposition) ModelName() string { return "user_with_composition" }

func (m *UserWithComposition) Schema() []model.Field { return UserWithCompositionModel.Fields }

func (m *UserWithComposition) Pointers() []any { return []any{&m.Id, &m.Name, &m.HomeAddr} }

func (m *UserWithComposition) IsNil() bool { return m == nil }

func (m *UserWithComposition) EncodeFields(w model.FieldWriter) {
	w.String("id", m.Id)
	w.String("name", m.Name)
	w.Object("home_addr", &m.HomeAddr)
}

func (m *UserWithComposition) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok { m.Id = v }
	if v, ok := r.String("name"); ok { m.Name = v }
	r.Object("home_addr", &m.HomeAddr)
}

type UserWithCompositionList []*UserWithComposition

func (s *UserWithCompositionList) Schema() []model.Field { return nil }
func (s *UserWithCompositionList) Pointers() []any     { return nil }
func (s *UserWithCompositionList) Len() int             { return len(*s) }
func (s *UserWithCompositionList) At(i int) model.Fielder { return (*s)[i] }
func (s *UserWithCompositionList) Append() model.Fielder  { v := &UserWithComposition{}; *s = append(*s, v); return v }
func (s *UserWithCompositionList) IsNil() bool          { return s == nil }
func (s *UserWithCompositionList) EncodeFields(_ model.FieldWriter) {}
func (s *UserWithCompositionList) DecodeFields(_ model.FieldReader) {}

func (m *UserWithComposition) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var UserWithComposition_ = struct {
	Id string
	Name string
	HomeAddr string
}{
	Id: "id",
	Name: "name",
	HomeAddr: "home_addr",
}

func ReadOneUserWithComposition(qb *orm.QB, model *UserWithComposition) (*UserWithComposition, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllUserWithComposition(qb *orm.QB) (UserWithCompositionList, error) {
	var results UserWithCompositionList
	err := qb.ReadAll(
		func() model.Model { return &UserWithComposition{} },
		func(m model.Model) { results = append(results, m.(*UserWithComposition)) },
	)
	return results, err
}

type UserWithNoTilde struct {
	Id string
	Nombre string
}

func (m *UserWithNoTilde) ModelName() string { return "user_with_no_tilde" }

func (m *UserWithNoTilde) Schema() []model.Field { return UserWithNoTildeModel.Fields }

func (m *UserWithNoTilde) Pointers() []any { return []any{&m.Id, &m.Nombre} }

func (m *UserWithNoTilde) IsNil() bool { return m == nil }

func (m *UserWithNoTilde) EncodeFields(w model.FieldWriter) {
	w.String("id", m.Id)
	w.String("nombre", m.Nombre)
}

func (m *UserWithNoTilde) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok { m.Id = v }
	if v, ok := r.String("nombre"); ok { m.Nombre = v }
}

type UserWithNoTildeList []*UserWithNoTilde

func (s *UserWithNoTildeList) Schema() []model.Field { return nil }
func (s *UserWithNoTildeList) Pointers() []any     { return nil }
func (s *UserWithNoTildeList) Len() int             { return len(*s) }
func (s *UserWithNoTildeList) At(i int) model.Fielder { return (*s)[i] }
func (s *UserWithNoTildeList) Append() model.Fielder  { v := &UserWithNoTilde{}; *s = append(*s, v); return v }
func (s *UserWithNoTildeList) IsNil() bool          { return s == nil }
func (s *UserWithNoTildeList) EncodeFields(_ model.FieldWriter) {}
func (s *UserWithNoTildeList) DecodeFields(_ model.FieldReader) {}

func (m *UserWithNoTilde) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var UserWithNoTilde_ = struct {
	Id string
	Nombre string
}{
	Id: "id",
	Nombre: "nombre",
}

func ReadOneUserWithNoTilde(qb *orm.QB, model *UserWithNoTilde) (*UserWithNoTilde, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllUserWithNoTilde(qb *orm.QB) (UserWithNoTildeList, error) {
	var results UserWithNoTildeList
	err := qb.ReadAll(
		func() model.Model { return &UserWithNoTilde{} },
		func(m model.Model) { results = append(results, m.(*UserWithNoTilde)) },
	)
	return results, err
}

type ShortAutoInc struct {
	Id int64
	Value int64
}

func (m *ShortAutoInc) ModelName() string { return "short_auto_inc" }

func (m *ShortAutoInc) Schema() []model.Field { return ShortAutoIncModel.Fields }

func (m *ShortAutoInc) Pointers() []any { return []any{&m.Id, &m.Value} }

func (m *ShortAutoInc) IsNil() bool { return m == nil }

func (m *ShortAutoInc) EncodeFields(w model.FieldWriter) {
	w.Int("id", m.Id)
	w.Int("value", m.Value)
}

func (m *ShortAutoInc) DecodeFields(r model.FieldReader) {
	if v, ok := r.Int("id"); ok { m.Id = v }
	if v, ok := r.Int("value"); ok { m.Value = v }
}

type ShortAutoIncList []*ShortAutoInc

func (s *ShortAutoIncList) Schema() []model.Field { return nil }
func (s *ShortAutoIncList) Pointers() []any     { return nil }
func (s *ShortAutoIncList) Len() int             { return len(*s) }
func (s *ShortAutoIncList) At(i int) model.Fielder { return (*s)[i] }
func (s *ShortAutoIncList) Append() model.Fielder  { v := &ShortAutoInc{}; *s = append(*s, v); return v }
func (s *ShortAutoIncList) IsNil() bool          { return s == nil }
func (s *ShortAutoIncList) EncodeFields(_ model.FieldWriter) {}
func (s *ShortAutoIncList) DecodeFields(_ model.FieldReader) {}

func (m *ShortAutoInc) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var ShortAutoInc_ = struct {
	Id string
	Value string
}{
	Id: "id",
	Value: "value",
}

func ReadOneShortAutoInc(qb *orm.QB, model *ShortAutoInc) (*ShortAutoInc, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllShortAutoInc(qb *orm.QB) (ShortAutoIncList, error) {
	var results ShortAutoIncList
	err := qb.ReadAll(
		func() model.Model { return &ShortAutoInc{} },
		func(m model.Model) { results = append(results, m.(*ShortAutoInc)) },
	)
	return results, err
}

