//go:build !wasm

package tests


import (
	"os"
	"strings"
	"testing"

	"webtyp.com/ormc"
)

func TestOrmc(t *testing.T) {
	t.Run("Generate User", func(t *testing.T) {
		o := ormc.New()
		cwd, _ := os.Getwd()
		o.SetRootDir(cwd)

		err := o.Run()
		if err != nil {
			t.Fatalf("Run() failed: %v", err)
		}

		outFile := "models_orm.go"
		contentBytes, err := os.ReadFile(outFile)
		if err != nil {
			t.Fatalf("Failed to read generated file: %v", err)
		}
		// defer os.Remove(outFile)

		content := string(contentBytes)

		expectedStrings := []string{
			"// DO NOT EDIT. generated by webtyp.com/ormc",
			"package tests",
			"func (m *User) ModelName() string { return \"user\" }",
			"func (m *User) Schema() []model.Field { return UserModel.Fields }",
			"func (m *User) Pointers() []any { return []any{&m.Id, &m.FirstName, &m.LastName, &m.Email, &m.Score, &m.IsActive, &m.Avatar} }",
			"func ReadOneUser(qb *orm.QB, model *User) (*User, error) {",
			"func ReadAllUser(qb *orm.QB) (UserList, error) {",
			"type UserList []*User",
			"func (m *User) EncodeFields(w model.FieldWriter) {",
			"func (m *User) DecodeFields(r model.FieldReader) {",
		}

		for _, expected := range expectedStrings {
			if !strings.Contains(content, expected) {
				t.Errorf("Generated file missing expected string: %s", expected)
			}
		}
	})

	t.Run("Generate Order With Refs", func(t *testing.T) {
		outFile := "models_orm.go"
		contentBytes, err := os.ReadFile(outFile)
		if err != nil {
			t.Fatalf("Failed to read generated file: %v", err)
		}
		content := string(contentBytes)

		expectedStrings := []string{
			"func (m *Order) SchemaExt() []model.FieldExt {",
			"Ref: \"user\", RefColumn: \"id\"",
			"var User_ = struct {",
		}

		for _, expected := range expectedStrings {
			if !strings.Contains(content, expected) {
				t.Errorf("Generated file missing expected string: %s", expected)
			}
		}
	})
}
